name: Validate Terraform Argo
on: 
  workflow_call:
    inputs:
      BUILD_PLATFORMS:
        description: 'Comma separated list of targets for builds e.g. "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"'
        default: "linux/amd64,linux/arm64,linux/ppc64le,linux/s390x"
        required: false
        type: string    
  push:
    branches: ["main", "release*"]
    tags: ["*"]
  pull_request:
    branches: ["main", "release*"]

env:
  GO_VERSION: "1.17"
  CONTROLLER_IMAGE: "quay.io/rcook/argocd-terraform-controller:latest"
  
jobs:
  build-controller:
    name: Build-controller
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test
        run: make test

      - name: Build controller container
        run: make docker-build IMG=${CONTROLLER_IMAGE}

      - name: Export container image
        run: docker save -o /tmp/controller.tar ${CONTROLLER_IMAGE}

      - name: Save container as artifact
        uses: actions/upload-artifact@v1
        with:
          name: controller
          path: /tmp/controller.tar

  push-controller:
    name: Push controller image to registry
    needs: [build-controller]
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug

      - name: Login to the registry
        run: |
          [[ "${CONTROLLER_IMAGE}" =~ ^([^/]+)/[^/]+/[^/]+ ]] && REGISTRY="${BASH_REMATCH[1]}" || REGISTRY="quay.io"
          echo "Attempting docker login to: ${REGISTRY}"
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin ${REGISTRY}
   
      - name: "Build Operator Image"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: "./Dockerfile"
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ env.CONTROLLER_IMAGE }}:latest